server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - regex:
          expression: '^/var/lib/docker/containers/(?P<container_id>[^/]+)/[^-]+-json\.log$'
          source: filename
      - docker:
          host: unix:///var/run/docker.sock
          refresh_interval: 5s
          match_source_labels: [ container_id ]
      - regex:
          expression: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z\s+\w+\s+\d+\s+---\s+\[(?P<app_name>[^\]]+)\]'
          source: output
      - labels:
          container_id:
          container_name:
          image_name:
          stream:
          app_name: